apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: hlu3uaa2o-python
  janus-idp.io/tekton: hlu3uaa2o-python
  backstage.io/kubernetes-id: hlu3uaa2o-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hlu3uaa2o-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
