apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: hlu3uaa2o-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hlu3uaa2o-python 
  name: hlu3uaa2o-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: hlu3uaa2o-python 
